INSERT INTO `#__admin_menu` (`id`, `title`, `link`, `pic`, `parent`, `order`) VALUES
(1, 'Main', '', '', 0, 0),
(2, 'Control Panel Home', 'index.php', 'home_small.png', 1, 0),
(3, 'Logout', 'index.php?pack=login&task=logout', 'false.png', 1, 1),
(4, 'Configuration', 'index.php?pack=config', '', 0, 1),
(5, 'System Configuration', 'index.php?pack=config&view=config', 'config.png', 4, 0),
(6, 'Default User Parameters', 'index.php?pack=config&view=defaults', 'apply.png', 4, 1),
(7, 'Packages', 'index.php?pack=config&view=extension&extype=package', 'package.png', 4, 2),
(8, 'Modules', 'index.php?pack=config&view=extension&extype=module', 'module.png', 4, 3),
(9, 'Plug-ins', 'index.php?pack=config&view=extension&extype=plugin', 'plugin.png', 4, 4),
(10, 'Crons', 'index.php?pack=config&view=extension&extype=cron', 'cron.png', 4, 5),
(11, 'Templates', 'index.php?pack=config&view=extension&extype=template', 'template.png', 4, 6),
(12, 'Users', '', '', 0, 2),
(13, 'Users list', 'index.php?pack=user', 'user.png', 12, 0),
(14, 'Activation waiting list', 'index.php?pack=user&view=moderation', 'switch.png', 12, 1),
(15, 'Usergroups', 'index.php?pack=usergroup', 'usergroup.png', 12, 2),
(16, 'Content', '', '', 0, 3),
(17, 'Blog Posts', 'index.php?pack=blog', 'blog.png', 16, 0),
(18, 'Blog Categories', 'index.php?pack=blog&view=category', 'category.png', 16, 1),
(19, 'Pages', 'index.php?pack=pages', 'pages.png', 16, 2),
(20, 'Packages', '', '', 0, 4),
(21, 'Modules Management', 'index.php?pack=modules', 'module.png', 20, 0),
(22, 'Website Links', 'index.php?pack=links', 'link.png', 20, 1),
(23, 'Link Groups', 'index.php?pack=links&view=grouplist', 'linkgroup.png', 22, 2),
(24, 'Quicklink Management', 'index.php?pack=quicklink_manager', 'quicklink.png', 20, 3),
(25, 'Languages Management', 'index.php?pack=language', 'languages.png', 20, 4),
(26, 'Extensions', '', '', 0, 5),
(27, 'Install / Uninstall / Manage', 'index.php?pack=installer', 'package.png', 26, 0),
(28, 'Tools', '', '', 0, 6),
(29, 'Website Tools', 'index.php?pack=tools', 'tools.png', 28, 0),
(30, 'Clean System Cache', 'index.php?pack=tools&task=cleanCache', 'trash.png', 28, 1),
(31, 'System Info', 'index.php?pack=info', 'info.png', 28, 3),
(32, 'Domains Management', 'index.php?pack=domains', 'domain.png', 20, 2);


INSERT INTO `#__blogcategories` (`id`, `title`, `sef_alias`, `desc`, `parent`, `accmask`) VALUES
(1, 'Default Category', 'default-category', '', 0, '');


INSERT INTO `#__blogposts` (`id`, `title`, `sef_alias`, `introcontent`, `morecontent`, `enabled`, `denied`, `blogid`, `added_by`, `added_time`, `mod_by`, `mod_time`, `pub_time`, `unpub_time`, `hits`, `rating`, `rate_count`, `tags`) VALUES
(1, 'Hello, World! سلام، دنیا!', 'helloworld', '<p>This is just an example post. Please delete or edit this post by adding your contents.</p>', '', 1, '', 1, {$RAND}, '2010-12-09 21:02:21', {$RAND}, '2010-12-09 21:02:21', '2010-12-09 21:02:21', NULL, 0, 0, 0, '');


INSERT INTO `#__cache_cleaning` (`table`, `cache_name`, `cached_fields`, `ext_unique`) VALUES
('#__blogposts', 'blog,sef_aliases', 'id,sef_alias', ''),
('#__blogposts', 'blog,new_tags', 'tags', ''),
('#__blogcategories', 'blog,cat_sef_aliases', 'id,sef_alias', ''),
('#__blogcategories', 'blog,new_categories', '', ''),
('#__blogcategories', 'blog,categories', '', ''),
('#__blogcategories', 'blog,denied_blogids', '', ''),
('#__userfields', 'user,guest', '', ''),
('#__quicklink', 'module_quicklink,items', '', ''),
('#__users', 'user,sef_aliases', 'id,username', ''),
('#__crons', 'cron,tasks', '', ''),
('#__plugins', 'plugin,site_files', '', ''),
('#__plugins', 'plugin,admin_files', '', ''),
('#__languages', 'plugin_translate,langids', 'id,name', ''),
('#__links', 'links,default', '', ''),
('#__packages', 'package,items', '', ''),
('#__modules', 'module,site_items', '', ''),
('#__modules', 'module,admin_items', '', ''),
('#__links', 'links,items_bygroup', '', ''),
('#__domains', 'domain,data', '', '');


INSERT INTO `#__crons` (`id`, `title`, `cron`, `enabled`, `runloop`, `nextrun`, `lastrun`, `core`) VALUES
(1, 'Inactive users cleanup', 'inactive_users_cleaner', 1, '259200', '1292087249', '1291828049', 1),
(2, 'Database tables Optimizer', 'tables_optimizer', 1, '604800', '1292432849', '1291828049', 1);


INSERT INTO `#__extensions_info` (`client`, `extype`, `extname`, `version`, `core`) VALUES
('admin', 'imageset', 'default', '{$VERSION}', 1),
('admin', 'language', 'en-US', '{$VERSION}', 1),
('admin', 'language', 'fa-IR', '{$VERSION}', 0),
('admin', 'module', 'buttons', '{$VERSION}', 1),
('admin', 'module', 'leftmenu', '{$VERSION}', 1),
('admin', 'module', 'menu', '{$VERSION}', 1),
('admin', 'module', 'popup_menu', '{$VERSION}', 1),
('admin', 'module', 'quicklink', '{$VERSION}', 1),
('admin', 'module', 'tabs', '{$VERSION}', 1),
('admin', 'module', 'tip', '{$VERSION}', 1),
('admin', 'module', 'topcontrols', '{$VERSION}', 1),
('admin', 'package', 'blog', '{$VERSION}', 1),
('admin', 'package', 'captcha', '{$VERSION}', 1),
('admin', 'package', 'config', '{$VERSION}', 1),
('admin', 'package', 'cphome', '{$VERSION}', 1),
('admin', 'package', 'filemanager', '{$VERSION}', 1),
('admin', 'package', 'info', '{$VERSION}', 1),
('admin', 'package', 'installer', '{$VERSION}', 1),
('admin', 'package', 'language', '{$VERSION}', 1),
('admin', 'package', 'links', '{$VERSION}', 1),
('admin', 'package', 'login', '{$VERSION}', 1),
('admin', 'package', 'modules', '{$VERSION}', 1),
('admin', 'package', 'pages', '{$VERSION}', 1),
('admin', 'package', 'quicklink_manager', '{$VERSION}', 1),
('admin', 'package', 'search', '{$VERSION}', 1),
('admin', 'package', 'tools', '{$VERSION}', 1),
('admin', 'package', 'user', '{$VERSION}', 1),
('admin', 'package', 'usergroup', '{$VERSION}', 1),
('admin', 'package', 'xmlrpc', '{$VERSION}', 1),
('admin', 'plugin', 'authorization', '{$VERSION}', 1),
('admin', 'plugin', 'news', '{$VERSION}', 1),
('admin', 'template', 'default', '{$VERSION}', 1),
('site', 'cron', 'inactive_users_cleaner', '{$VERSION}', 1),
('site', 'cron', 'tables_optimizer', '{$VERSION}', 1),
('site', 'imageset', 'default', '{$VERSION}', 1),
('site', 'language', 'en-US', '{$VERSION}', 1),
('site', 'language', 'fa-IR', '{$VERSION}', 0),
('site', 'module', 'blogcats', '{$VERSION}', 1),
('site', 'module', 'bloglast', '{$VERSION}', 1),
('site', 'module', 'blogmost', '{$VERSION}', 1),
('site', 'module', 'langselector', '{$VERSION}', 1),
('site', 'module', 'linkviewer', '{$VERSION}', 1),
('site', 'module', 'login', '{$VERSION}', 1),
('site', 'module', 'pathway', '{$VERSION}', 1),
('site', 'module', 'search', '{$VERSION}', 1),
('site', 'module', 'stats', '{$VERSION}', 1),
('site', 'plugin', 'code_highlight', '{$VERSION}', 1),
('site', 'plugin', 'contentrating', '{$VERSION}', 1),
('site', 'plugin', 'guess_userlang', '{$VERSION}', 1),
('site', 'plugin', 'oembed_handler', '{$VERSION}', 1),
('site', 'plugin', 'searchblog', '{$VERSION}', 1),
('site', 'plugin', 'searchpages', '{$VERSION}', 1),
('site', 'plugin', 'translate', '{$VERSION}', 1),
('site', 'plugin', 'visitor_msgs', '{$VERSION}', 1),
('site', 'template', 'default', '{$VERSION}', 1),
('site', 'webservice', 'api_metaweblog', '{$VERSION}', 1),
('site', 'webservice', 'info', '{$VERSION}', 1),
('site', 'widget', 'bloglast', '{$VERSION}', 1),
('site', 'widget', 'blogmost', '{$VERSION}', 1),
('site', 'widget', 'blogposts_viewer', '{$VERSION}', 1),
('site', 'widget', 'customphp', '{$VERSION}', 1),
('site', 'widget', 'file_viewer', '{$VERSION}', 1),
('site', 'widget', 'linkviewer', '{$VERSION}', 1),
('site', 'widget', 'modviewer', '{$VERSION}', 1),
('*', 'plugin', 'ipblocker', '{$VERSION}', 1),
('*', 'plugin', 'url', '{$VERSION}', 1),
('site', 'plugin', 'censorship', '{$VERSION}', 1),
('admin', 'package', 'domains', '{$VERSION}', 1);


INSERT INTO `#__imagesets` (`id`, `name`, `title`, `designer`, `client`, `core`) VALUES
(1, 'default', 'Default', 'Mehran Ahadi', 'site', 1),
(2, 'default', 'Default', 'Mehran Ahadi', 'admin', 1);


INSERT INTO `#__languages` (`id`, `name`, `title`, `designer`, `client`, `core`) VALUES
(1, 'en-US', 'English', 'Mehran Ahadi', 'site', 1),
(2, 'en-US', 'English', 'Mehran Ahadi', 'admin', 1),
(3, 'fa-IR', 'Persian (پارسی)', 'Mehran Ahadi', 'site', 0),
(4, 'fa-IR', 'Persian (پارسی)', 'Mehran Ahadi', 'admin', 0);


INSERT INTO `#__links` (`id`, `title`, `link`, `type`, `group`, `enabled`, `denied`, `newwin`, `order`) VALUES
(1, 'Homepage', 'index.php?pack=blog', 'default', 1, 1, '', 0, 0),
(2, 'Blog Index', 'index.php?pack=blog&view=index', 'inner', 1, 1, '', 0, 1),
(3, 'Your Details', 'index.php?pack=user&view=edit', 'inner', 2, 1, '', 0, 0),
(4, 'Your Notes', 'index.php?pack=user&view=notes', 'inner', 2, 1, '', 0, 1),
(5, 'Members List', 'index.php?pack=user&view=list', 'inner', 2, 1, '', 0, 2),
(6, 'Media Manager', 'index.php?pack=filemanager', 'inner', 2, 1, '-2', 0, 3),
(7, 'New Blog Post', 'index.php?pack=blog&view=new', 'inner', 2, 1, '-2', 0, 4),
(8, 'New Page', 'index.php?pack=pages&view=new', 'inner', 2, 1, '-2', 0, 5);


INSERT INTO `#__link_groups` (`id`, `title`) VALUES
(1, 'Default'),
(2, 'User Links');


INSERT INTO `#__modules` (`id`, `title`, `order`, `location`, `enabled`, `showat`, `denied`, `module`, `content`, `showtitle`, `core`, `client`) VALUES
(1, 'Login / Logout', 0, 'header', 1, '', '', 'login', '', 0, 1, 'site'),
(2, 'Top menu', 0, 'top', 1, '', '', 'menu', '', 0, 1, 'admin'),
(3, 'Admin Buttons', 0, 'custom3', 1, '', '', 'buttons', '', 0, 1, 'admin'),
(4, 'QuickLink', 0, 'header', 1, '', '', 'quicklink', '', 0, 1, 'admin'),
(5, 'Pathway Indicator', 0, 'pathway', 1, '', '', 'pathway', '', 0, 1, 'site'),
(6, 'Blog Categories', 4, 'left', 1, '', '', 'blogcats', '', 1, 1, 'site'),
(7, 'Latest Posts', 2, 'left', 1, '', '', 'bloglast', '', 1, 1, 'site'),
(8, 'Search', 0, 'custom1', 1, '', '', 'search', '', 0, 1, 'site'),
(9, 'Most Popular Posts', 3, 'left', 1, '', '', 'blogmost', '', 1, 1, 'site'),
(10, 'Website Statistics', 5, 'left', 1, '', '', 'stats', '', 1, 1, 'site'),
(11, 'Left Menu', 0, 'left', 0, '', '', 'leftmenu', '', 0, 1, 'admin'),
(12, 'Tabs', 0, 'custom4', 1, '', '', 'tabs', '', 0, 1, 'admin'),
(13, 'Top Controls', 0, 'custom1', 1, '', '', 'topcontrols', '', 0, 1, 'admin'),
(14, 'Administration Tips', 0, 'custom2', 1, '', '', 'tip', '', 0, 1, 'admin'),
(15, 'Language Selector', 1, 'header', 1, '', '', 'langselector', '', 0, 1, 'site'),
(16, 'Main Menu', 0, 'left', 1, '', '', 'linkviewer', 'MENU:1', 1, 0, 'site'),
(17, 'User Menu', 1, 'left', 1, '', '0', 'linkviewer', 'MENU:2', 1, 0, 'site');


INSERT INTO `#__packages` (`id`, `name`, `title`, `core`, `enabled`, `denied`) VALUES
(1, 'user', 'Users', 1, 1, ''),
(2, 'login', 'Administration Login', 1, 1, ''),
(3, 'cphome', 'Control Panel Home', 1, 1, ''),
(4, 'config', 'Configuration', 1, 1, ''),
(5, 'tools', 'Website Tools', 1, 1, ''),
(6, 'xmlrpc', 'Web Services Handler', 1, 1, ''),
(7, 'usergroup', 'Usergroups Manager', 1, 1, ''),
(8, 'filemanager', 'File and Media Manager', 1, 1, ''),
(9, 'captcha', 'Human Verification Image Generator', 1, 1, ''),
(10, 'blog', 'Blog', 1, 1, ''),
(11, 'search', 'Search', 1, 1, ''),
(12, 'installer', 'Extension Installer', 1, 1, ''),
(13, 'modules', 'Modules Manager', 1, 1, ''),
(14, 'links', 'Links Manager', 1, 1, ''),
(15, 'info', 'System Information', 1, 1, ''),
(16, 'quicklink_manager', 'Quicklink Manager', 1, 1, ''),
(17, 'pages', 'Custom Pages', 1, 1, ''),
(18, 'language', 'Languages Manager', 1, 1, ''),
(19, 'domains', 'Domains Manager', 1, 1, '');


INSERT INTO `#__pages_widgets_resource` (`id`, `title`, `filename`, `core`) VALUES
(1, 'Blog Posts Viewer', 'blogposts_viewer', 1),
(2, 'Module Viewer', 'modviewer', 1),
(3, 'Custom PHP Code', 'customphp', 1),
(4, 'File viewer', 'file_viewer', 1),
(5, 'Blog last posts', 'bloglast', 1),
(6, 'Popular posts', 'blogmost', 1),
(7, 'Link Viewer', 'linkviewer', 1);


INSERT INTO `#__plugins` (`id`, `title`, `plugin`, `group`, `order`, `enabled`, `denied`, `core`, `client`) VALUES
(1, 'Administrator Panel user detection', 'authorization', 'system', 0, 1, '', 1, 'admin'),
(2, 'URL Processor', 'url', 'system', 0, 1, '', 1, '*'),
(3, 'Blog Search', 'searchblog', 'search', 0, 1, '', 1, 'site'),
(4, 'Blog Content Rating', 'contentrating', 'content', 0, 1, '', 1, 'site'),
(5, 'Visitor Messages', 'visitor_msgs', 'profile', 0, 1, '', 1, 'site'),
(6, 'IP Blocker', 'ipblocker', 'system', 0, 1, '', 1, '*'),
(7, 'Pages Search', 'searchpages', 'search', 1, 1, '', 1, 'site'),
(8, 'Content Translator', 'translate', 'content', 0, 1, '', 1, 'site'),
(9, 'Latest News and Updates on CP Home', 'news', 'cphome', 1, 1, '', 1, 'admin'),
(10, 'Code Highlighter', 'code_highlight', 'content', 1, 1, '', 1, 'site'),
(11, 'OEmbed Handler', 'oembed_handler', 'content', 1, 1, '', 1, 'site'),
(12, 'Guess User Language', 'guess_userlang', 'system', 0, 1, '', 1, 'site'),
(13, 'Badwords Censorship', 'censorship', 'content', 1, 0, '', 1, 'site');


INSERT INTO `#__quicklink` (`id`, `title`, `link`, `alt`, `img`, `acckey`, `order`) VALUES
(1, 'Control Panel Home', 'index.php?pack=cphome', 'Control panel homepage.', 'home.png', 'ctrl+alt+h', 1),
(2, 'System Configuration', 'index.php?pack=config&view=config', 'Manage system configuration including Website name, Keywords, DB, Cache, E-Mail, FTP and other settings.', 'config.png', 'ctrl+alt+c', 2),
(3, 'Users', 'index.php?pack=user', 'Add, edit, activate or delete user accounts.', 'user.png', 'ctrl+alt+u', 3),
(4, 'Blog Posts', 'index.php?pack=blog', 'Manage Blog posts and post comments', 'blog.png', 'ctrl+alt+b', 4),
(5, 'Pages', 'index.php?pack=pages', 'Manage pages and page widgets', 'pages.png', 'ctrl+alt+p', 5),
(6, 'Modules', 'index.php?pack=modules', 'Manage Site and Admin modules.', 'module.png', 'ctrl+alt+m', 6),
(7, 'Website Links', 'index.php?pack=links', 'Manage Website links', 'link.png', 'ctrl+alt+l', 7),
(8, 'Languages', 'index.php?pack=language', 'Manage Content translation items and find missing languages files.', 'languages.png', 'ctrl+alt+t', 8),
(9, 'Extensions', 'index.php?pack=installer', 'Install / Uninstall / Manage the extensions.', 'package.png', 'ctrl+alt+e', 9),
(10, 'Tools', 'index.php?pack=tools', 'Useful tools for tweaking and testing system.', 'tools.png', 'ctrl+alt+y', 10);


INSERT INTO `#__settings` (`var`, `value`, `default`, `extype`, `extname`, `client`, `vartype`, `vartypedata`, `check`) VALUES
('header', 's:0:"";', 's:0:"";', 'package', 'user', 'site', 'text', NULL, NULL),
('username_min_length', 'i:3;', 'i:3;', 'package', 'user', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 3){$value=3;}'),
('password_min_length', 'i:6;', 'i:6;', 'package', 'user', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 5){$value=5;}'),
('default_ug', 's:1:"1";', 's:1:"1";', 'package', 'user', 'site', 'usergroups', NULL, '$items=ArtaUserGroup::getItems();\r\n$s=false;\r\nforeach($items as $k=>$v){\r\nif($v->id == $value){\r\n$s=true;\r\ncontinue;\r\n}\r\n}\r\nif($s==false){$error=trans(''INVALID USERGROUP'');}'),
('activation_mode', 's:1:"0";', 's:1:"0";', 'package', 'user', 'site', 'radio', '$options[''options'']=array(0=>trans(''NO_ACTIVATION''),\r\n1=>trans(''BY_MAIL''),2=>trans(''BY_MODERATOR''));\r\n', 'if(!($value==0 || $value==1 || $value==2)){\r\n$error=trans(''INVALID ACTIVATION_MODE VALUE'');\r\n}'),
('allow_registering', 'b:1;', 'b:1;', 'package', 'user', 'site', 'bool', NULL, NULL),
('redirect_to_location', 's:0:"";', 's:0:"";', 'module', 'login', 'site', 'text', NULL, '$value=trim((string)$value);'),
('module_prefix_txt', 's:0:"";', 's:0:"";', 'module', 'login', 'site', 'text', NULL, NULL),
('module_suffix_txt', 's:0:"";', 's:0:"";', 'module', 'login', 'site', 'text', NULL, NULL),
('show_username', 'b:0;', 'b:0;', 'module', 'login', 'site', 'bool', NULL, NULL),
('greeting_msg', 's:23:"Welcome to our website!";', 's:23:"Welcome to our website!";', 'module', 'login', 'site', 'text', NULL, NULL),
('direction', 's:3:"hor";', 's:3:"hor";', 'module', 'buttons', 'admin', 'radio', '$options[''options'']=array(''hor''=>trans(''HORIZONTAL''),\r\n''ver''=>trans(''VERTICAL''));', 'if(!($value==''hor'' || $value==''ver'')){$value=''hor'';}'),
('layout', 's:7:"fisheye";', 's:7:"fisheye";', 'module', 'quicklink', 'admin', 'radio', '$options[''options'']=array(''icon''=>trans(''ICON''),''list''=>trans(''LIST''),''fisheye''=>trans(''FISHEYE''));', 'if(!($value==''icon'' || $value==''list'' || $value==''fisheye'')){$error=trans(''INVALID LAYOUT SELECTED'');}'),
('denied_username', 'a:3:{i:0;s:5:"admin";i:1;s:6:"leader";i:2;s:9:"moderator";}', 'a:3:{i:0;s:5:"admin";i:1;s:6:"leader";i:2;s:9:"moderator";}', 'package', 'user', 'site', 'custom', 'echo ''<textarea name=''.$name.''>''.implode($value,'','').''</textarea>'';', '$value=ArtaString::split($value,'','');'),
('captcha_length', 'i:6;', 'i:6;', 'package', 'captcha', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value<3){ $value=3; }'),
('captcha_format', 's:3:"png";', 's:3:"png";', 'package', 'captcha', 'site', 'select', '$options[''options'']=array( ''png''=>''PNG'', ''jpg''=>''JPEG'', ''gif''=>''GIF'' );', '$valid=array(''png'',''gif'',''jpg''); if(!in_array($value, $valid)){ $value=''png''; }'),
('use_blur', 'b:1;', 'b:1;', 'package', 'captcha', 'site', 'bool', NULL, NULL),
('use_noise', 'b:1;', 'b:1;', 'package', 'captcha', 'site', 'bool', NULL, NULL),
('use_signs', 'b:1;', 'b:1;', 'package', 'captcha', 'site', 'bool', NULL, NULL),
('allowed_filetypes_to_upload', 's:149:"jpg,jpeg,gif,png,swf,flv,bmp,psd,mp3,wav,wma,wm,asf,mp4,mpg,mpeg,avi,wmv,mkv,3gp,rm,zip,rar,7z,gz,bz,tar,doc,pdf,xls,wri,docx,rtf,sis,jar,cab,apk,txt";', 's:149:"jpg,jpeg,gif,png,swf,flv,bmp,psd,mp3,wav,wma,wm,asf,mp4,mpg,mpeg,avi,wmv,mkv,3gp,rm,zip,rar,7z,gz,bz,tar,doc,pdf,xls,wri,docx,rtf,sis,jar,cab,apk,txt";', 'package', 'filemanager', 'site', 'textbox', NULL, NULL),
('allowed_filesize_to_upload', 'i:4096;', 'i:4096;', 'package', 'filemanager', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value<0){\r\n$value=0;\r\n}'),
('show_first_last_name', 'b:1;', 'b:1;', 'package', 'blog', 'site', 'bool', NULL, NULL),
('show_blockmsg_for_denied_users', 'b:0;', 'b:0;', 'package', 'blog', 'site', 'bool', NULL, NULL),
('rating_timer', 'i:3600;', 'i:3600;', 'package', 'blog', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');'),
('link_type', 's:4:"last";', 's:4:"last";', 'module', 'blogcats', 'site', 'radio', '$options[''options'']=array(''last''=>trans(''blog_layout''), ''index''=>trans(''index_layout''));', 'if($value!=''index'' && $value!=''last''){\r\n$value=''last'';\r\n}'),
('blogid_to_show', 's:1:"0";', 's:1:"0";', 'module', 'bloglast', 'site', 'custom', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT * FROM #__blogcategories'');\r\n$r=array(''-'');\r\nforeach($db->loadObjectList() as $v){\r\n$r[$v->id]=$v->title;\r\n}\r\necho self::select($name, $r, $value);', NULL),
('show_hits_count', 'b:1;', 'b:1;', 'module', 'bloglast', 'site', 'bool', NULL, NULL),
('last_limit', 'i:10;', 'i:10;', 'module', 'bloglast', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 1){$value=1;}'),
('blogid_to_show', 's:1:"0";', 's:1:"0";', 'module', 'blogmost', 'site', 'custom', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT * FROM #__blogcategories'');\r\n$r=array(''-'');\r\nforeach($db->loadObjectList() as $v){\r\n$r[$v->id]=$v->title;\r\n}\r\necho self::select($name, $r, $value);', NULL),
('show_hits_count', 'b:1;', 'b:1;', 'module', 'blogmost', 'site', 'bool', NULL, NULL),
('list_enabled', 'b:1;', 'b:1;', 'package', 'user', 'site', 'bool', NULL, NULL),
('show_onlines', 'b:1;', 'b:1;', 'module', 'stats', 'site', 'bool', NULL, NULL),
('link_onlines_profile', 'b:1;', 'b:1;', 'module', 'stats', 'site', 'bool', NULL, NULL),
('show_icons', 'b:0;', 'b:0;', 'module', 'leftmenu', 'admin', 'bool', NULL, NULL),
('blocked_ips', 's:0:"";', 's:0:"";', 'plugin', 'ipblocker', '*', 'textbox', '$options[''params'']=array(''height''=>200);', NULL),
('block_admin', 'b:0;', 'b:0;', 'plugin', 'ipblocker', '*', 'bool', NULL, NULL),
('redirection_url', 's:0:"";', 's:0:"";', 'plugin', 'ipblocker', '*', 'text', NULL, '$value=trim((string)$value);'),
('postid_to_show', 'N;', 'N;', 'widget', 'blogposts_viewer', 'site', 'custom', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT id,title FROM #__blogposts ORDER BY added_time DESC'');\r\n$posts = $db->loadObjectList();\r\n$data=array();\r\nforeach($posts as $c){\r\nif(!isset($first)){$first=$c->id;}\r\n$data[$c->id]=$c->title;\r\n}\r\necho ArtaTagsHtml::select($name, $data, $value);', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT id FROM #__blogposts WHERE id=''.$db->Quote($value));\r\n$r=$db->loadResult();\r\nif($r!==$value){\r\n$error=trans(''INVALID POSTID'');\r\n}'),
('rules_text', 's:148:"<p>1. Everybody must have an Unique Username (no duplicate registers)<br /> 2. Don''t reveal your Password to others<br /> 3. Respect the Leaders</p>";', 's:148:"<p>1. Everybody must have an Unique Username (no duplicate registers)<br /> 2. Don''t reveal your Password to others<br /> 3. Respect the Leaders</p>";', 'package', 'user', 'site', 'custom', 'echo ArtaTagsHtml::addEditor($name, $value);', NULL),
('show_icons', 'b:1;', 'b:1;', 'module', 'menu', 'admin', 'bool', NULL, NULL),
('lastposts_list_limit', 'i:6;', 'i:6;', 'package', 'blog', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 1){$value=1;}'),
('blogposts_generate_pdf_version', 'b:1;', 'b:1;', 'package', 'blog', 'site', 'bool', NULL, NULL),
('rssfeed_list_limit', 'i:15;', 'i:15;', 'package', 'blog', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 1){$value=1;}'),
('max_possible_rating_value', 'i:5;', 'i:5;', 'package', 'blog', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 3){$value=3;}'),
('search_times', 'i:15;', 'i:15;', 'package', 'search', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 1){$value=1;}'),
('search_timeout', 'i:5;', 'i:5;', 'package', 'search', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 0){$value=0;}'),
('rssfeed_alternate_url', 's:0:"";', 's:0:"";', 'package', 'blog', 'site', 'text', NULL, '$value=trim((string)$value);'),
('commenting_system', 'b:1;', 'b:1;', 'package', 'blog', 'site', 'bool', '$options[''no'']=trans(''OFF'');\r\n$options[''yes'']=trans(''ON'');', NULL),
('multilingual_comments', 'b:1;', 'b:1;', 'package', 'blog', 'site', 'bool', NULL, NULL),
('autopublish_comments', 'b:0;', 'b:0;', 'package', 'blog', 'site', 'bool', NULL, NULL),
('show_images', 'b:1;', 'b:1;', 'module', 'buttons', 'admin', 'bool', NULL, NULL),
('last_limit', 'i:10;', 'i:10;', 'module', 'blogmost', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');\r\nif($value < 1){$value=1;}'),
('show_full_content', 'b:0;', 'b:0;', 'widget', 'blogposts_viewer', 'site', 'bool', NULL, NULL),
('show_post_link', 'b:1;', 'b:1;', 'widget', 'blogposts_viewer', 'site', 'bool', NULL, NULL),
('color_variant', 's:4:"blue";', 's:4:"blue";', 'template', 'default', 'site', 'select', '$options[''options'']=array(\r\n''orange''=>trans(''ORANGE''),\r\n''blue''=>trans(''BLUE'')\r\n);', NULL),
('module_to_view', NULL, NULL, 'widget', 'modviewer', 'site', 'custom', '$db=ArtaLoader::DB(); $db->setQuery(''SELECT id,title FROM #__modules WHERE client=\\''site\\'' ORDER BY `order` ASC, location''); $mods = $db->loadObjectList(); $data=array(); foreach($mods as $c){ $data[$c->id]=$c->title; } echo ArtaTagsHtml::select($name, $data, $value);', '$db=ArtaLoader::DB(); $db->setQuery(''SELECT id FROM #__modules WHERE client=\\''site\\'' AND id=''.$db->Quote($value)); $r=$db->loadResult(); if($r!==$value){ $error=trans(''INVALID MODID''); }'),
('phpcode_to_run', NULL, NULL, 'widget', 'customphp', 'site', 'custom', 'echo ArtaTagsHtml::addCodeEditor($name, $value);', NULL),
('selected_files_to_show', 'N;', 'N;', 'widget', 'file_viewer', 'site', 'custom', '$_configuring=true;\r\ninclude ARTAPATH_BASEDIR.''/widgets/file_viewer.php'';', NULL),
('files_description', 'N;', 'N;', 'widget', 'file_viewer', 'site', 'custom', 'echo ArtaTagsHtml::addEditor($name, $value);', '$value=ArtaFilterinput::clean($value, ''safe-html'');'),
('view_layout', 's:1:"1";', 's:1:"1";', 'module', 'login', 'site', 'radio', '$options[''options'']=array(trans(''normal_view''), trans(''mini_view''), trans(''supermini_view''));', NULL),
('blogid_to_show', 'i:0;', 'i:0;', 'widget', 'bloglast', 'site', 'custom', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT * FROM #__blogcategories'');\r\n$r=array(''-'');\r\nforeach($db->loadObjectList() as $v){\r\n$r[$v->id]=$v->title;\r\n}\r\necho self::select($name, $r, $value);', '$value=ArtaFilterinput::clean($value,''int'');'),
('blogid_to_show', 'i:0;', 'i:0;', 'widget', 'blogmost', 'site', 'custom', '$db=ArtaLoader::DB();\r\n$db->setQuery(''SELECT * FROM #__blogcategories'');\r\n$r=array(''-'');\r\nforeach($db->loadObjectList() as $v){\r\n$r[$v->id]=$v->title;\r\n}\r\necho self::select($name, $r, $value);', '$value=ArtaFilterinput::clean($value,''int'');'),
('linkgroup_to_list', 'i:0;', 'i:0;', 'widget', 'linkviewer', 'site', 'custom', '$db=Artaloader::DB();\r\n$db->setQuery(''SELECT * FROM #__link_groups'');\r\n$grps=$db->loadObjectList(''id'');\r\nforeach($grps as $k=>$v){\r\n   $grps[$k]=$v->title;\r\n}\r\necho ArtaTagsHtml::select($name, $grps, $value);', '$value=ArtaFilterinput::clean($value,''int'');'),
('secure_login_over_https', 'b:0;', 'b:0;', 'package', 'user', 'site', 'bool', NULL, NULL),
('allow_openid_usage', 'b:1;', 'b:1;', 'package', 'user', 'site', 'custom', 'echo ArtaTagsHtml::PreFormItem($name, $value, ''bool'', ''$options["options"]=array(trans("NO"),trans("YES"));'').'' &nbsp;&nbsp;<a href="http://openid.net" target="_blank"><small>''.trans(''WHAT IS OPENID'').''</small></a>'';', '$value=@(bool)$value;'),
('secure_login_over_https', 'b:0;', 'b:0;', 'package', 'user', 'admin', 'bool', NULL, NULL),
('newposts_time_domain', 's:7:"2592000";', 's:7:"2592000";', 'module', 'blogmost', 'site', 'select', '$options[''options'']=array(\r\n604800=>trans(''ONE WEEK''),\r\n1209600=>trans(''TWO WEEKS''),\r\n1814400=>trans(''THREE WEEKS''),\r\n2592000=>trans(''ONE MONTH''),\r\n5184000=>trans(''TWO MONTHS''),\r\n7776000=>trans(''THREE MONTHS''),\r\n15724800=>trans(''SIX MONTHS''),\r\n31536000=>trans(''ONE YEAR''));', NULL),
('tip_view_mode', 's:5:"popup";', 's:5:"popup";', 'module', 'tip', 'admin', 'radio', '$options[''options'']=array(''simple''=>trans(''SIMPLE LAY''), ''popup''=>trans(''POPUP LAY''));', 'if(!in_array($value, array(''simple'',''popup'') )){\r\n$value=''simple'';\r\n}'),
('loginmiss_times', 'i:4;', 'i:4;', 'package', 'user', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');'),
('loginmiss_timeout', 'i:15;', 'i:15;', 'package', 'user', 'site', 'text', NULL, '$value=ArtaFilterinput::clean($value,''int'');'),
('staticpages_generate_pdf_version', 'b:1;', 'b:1;', 'package', 'pages', 'site', 'bool', NULL, NULL),
('bad_words', 's:0:"";', 's:0:"";', 'plugin', 'censorship', 'site', 'textbox', NULL, NULL),
('view_icons', 'b:1;', 'b:1;', 'module', 'langselector', 'site', 'bool', NULL, NULL);


INSERT INTO `#__templates` (`id`, `name`, `title`, `designer`, `client`, `core`) VALUES
(1, 'default', 'Default', 'Mehran Ahadi', 'site', 1),
(2, 'default', 'Default', 'Mehran Ahadi', 'admin', 1);


INSERT INTO `#__userfields` (`var`, `default`, `extype`, `extname`, `vartype`, `vartypedata`, `check`, `viewcode`, `fieldtype`, `show_on_register`) VALUES
('site_language', 's:5:"en-US";', 'library', 'language', 'languages', '$options[''client'']=''site'';', NULL, NULL, 'setting', 0),
('site_template', 's:7:"default";', 'library', 'template', 'templates', '$options[''client'']=''site'';', NULL, NULL, 'setting', 0),
('admin_language', 's:5:"en-US";', 'library', 'language', 'languages', '$options[''client'']=''admin'';', NULL, NULL, 'setting', 0),
('admin_template', 's:7:"default";', 'library', 'template', 'templates', '$options[''client'']=''admin'';', NULL, NULL, 'setting', 0),
('yahoo_id', 's:0:"";', 'package', 'user', 'text', NULL, NULL, 'echo ''<img src="''.ArtaURL::getSiteURL().''packages/user/assets/images/im_yahoo.png"> ''.$value;', 'misc', 1),
('site_imageset', 's:7:"default";', 'library', 'template', 'imagesets', '$options[''client'']=''site'';', NULL, NULL, 'setting', 0),
('admin_imageset', 's:7:"default";', 'library', 'template', 'imagesets', '$options[''client'']=''admin'';', NULL, NULL, 'setting', 0),
('time_offset', 'N;', 'library', 'config', 'custom', '$config=ArtaLoader::Config();\r\n$value= $value==null ? $config->time_offset : $value;\r\necho $scope==''defaults'' ? trans(''CHANGE THIS AT SYSCONFIG'') : ArtaTagsHtml::getTimezones($name, $value);', '$value= $scope==''defaults'' ? null : $value;', NULL, 'setting', 0),
('profile_page_order', 's:17:"a:1:{i:0;s:0:"";}";', 'package', 'user', 'custom', '$value=@(array)unserialize($value);\r\n$value=implode('','', $value);\r\n\r\nif(CLIENT==''site''){\r\necho trans(''YOU CAN CHANGE IT USING MOUSE AT PROFILE PAGE'');\r\necho self::text($name, $value, ''text'', array(''style''=>''display:none;''));\r\n}else{\r\necho self::text($name, $value);\r\n}', '$value=@(array)explode('','', $value);\r\n$value=serialize($value);', NULL, 'setting', 0),
('usertitle', 's:0:"";', 'package', 'user', 'custom', 'if(ArtaUsergroup::getPerm(''can_change_usertitle'', ''package'', ''user'', ''site'')){\r\necho self::text($name, $value);\r\n}else{\r\necho trans(''YOU CANNOT CHANGE YOUR TITLE'').''<input type="hidden" name="''.$name.''" value="">'';\r\n}', 'if(!ArtaUsergroup::getPerm(''can_change_usertitle'', ''package'', ''user'')){\r\n$value='''';\r\n}', NULL, 'setting', 0),
('cal_type', 'N;', 'library', 'config', 'custom', '$config=ArtaLoader::Config();\r\n$value= $value==null ? $config->cal_type : $value;\r\necho $scope==''defaults'' ? trans(''CHANGE THIS AT SYSCONFIG'') : ArtaTagsHtml::radio($name,\r\narray(''gregorian''=>trans(''gregorian''),\r\n''jalali''=>trans(''jalali'')\r\n),$value);', '$config=ArtaLoader::Config();\r\n$value= $scope==''defaults'' ? null : (in_array($value, \r\n   array(''gregorian'', ''jalali'')) ?\r\n   $value : $config->cal_type\r\n);', NULL, 'setting', 0),
('weburl', 's:0:"";', 'package', 'user', 'text', 'if(trim($value=='''')){\r\n$value="http://";\r\n}', 'if(trim($value==''http://'')){\r\n$value="";\r\n}', 'echo ''<img src="''.Imageset(''home_small.png'').''"/> <a href="''.htmlspecialchars($value).''" target="_blank">''.htmlspecialchars($value).''</a>'';\r\n', 'misc', 1),
('profile_msg', 's:0:"";', 'package', 'user', 'text', NULL, NULL, NULL, 'setting', 0),
('gtalk_id', 's:0:"";', 'package', 'user', 'text', NULL, NULL, 'echo ''<img src="''.ArtaURL::getSiteURL().''packages/user/assets/images/im_gtalk.png"> ''.$value;', 'misc', 1),
('disable_private_messaging', 'b:0;', 'package', 'user', 'bool', NULL, NULL, NULL, 'setting', 0),
('user_bio', 's:0:"";', 'package', 'user', 'textbox', NULL, NULL, NULL, 'misc', 0),
('user_location', 's:0:"";', 'package', 'user', 'text', NULL, NULL, NULL, 'misc', 0),
('user_interests', 's:0:"";', 'package', 'user', 'text', NULL, NULL, NULL, 'misc', 0),
('profile_theme', 's:6:"simple";', 'package', 'user', 'select', '$options[''options'']=array(\r\n''simple''=>trans(''SIMPLE''),\r\n''lime''=>trans(''LIME''),\r\n''orange''=>trans(''ORANGE''),\r\n''red''=>trans(''RED''),\r\n''blue''=>trans(''BLUE'')\r\n);', NULL, NULL, 'setting', 0);


INSERT INTO `#__usergroupperms` (`id`, `name`, `default`, `extname`, `extype`, `client`, `vartype`, `vartypedata`, `check`) VALUES
(1, 'can_delete_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(2, 'can_addedit_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(3, 'can_edit_others_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(4, 'can_publish_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(5, 'can_addedit_categories', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(6, 'can_delete_categories', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(7, 'can_edit_post_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(8, 'can_access_post_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(9, 'can_edit_others_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(10, 'can_change_comments_publish_status', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(11, 'can_delete_posts_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'admin', 'bool', NULL, NULL),
(12, 'can_edit_settings_package', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(13, 'can_edit_settings_module', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(14, 'can_edit_settings_plugin', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(15, 'can_edit_settings_template', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(16, 'can_edit_settings_cron', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(17, 'can_edit_settings_config', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(18, 'can_edit_settings_defaults', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'config', 'package', 'admin', 'bool', NULL, NULL),
(19, 'can_open_info', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'info', 'package', 'admin', 'bool', NULL, NULL),
(20, 'can_clear_logs_and_alerts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'info', 'package', 'admin', 'bool', NULL, NULL),
(21, 'can_install_extensions', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(22, 'can_uninstall_extensions', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(23, 'can_change_extensions_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(24, 'can_change_plugins_perms', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(25, 'can_change_packages_perms', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(26, 'can_change_crons_timings', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(28, 'can_access_installer', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(29, 'can_install_updates', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'installer', 'package', 'admin', 'bool', NULL, NULL),
(30, 'can_addedit_translations', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'language', 'package', 'admin', 'bool', NULL, NULL),
(31, 'can_remove_unusable_translations', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'language', 'package', 'admin', 'bool', NULL, NULL),
(32, 'can_delete_translations', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'language', 'package', 'admin', 'bool', NULL, NULL),
(33, 'can_change_translations_activation', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'language', 'package', 'admin', 'bool', NULL, NULL),
(36, 'can_edit_links_order', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(37, 'can_edit_links_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(38, 'can_addedit_links', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(39, 'can_delete_links', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(40, 'can_addedit_link_groups', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(41, 'can_delete_link_groups', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(42, 'can_set_default_link', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'links', 'package', 'admin', 'bool', NULL, NULL),
(43, 'can_edit_mod_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'modules', 'package', 'admin', 'bool', NULL, NULL),
(44, 'can_edit_mod_order', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'modules', 'package', 'admin', 'bool', NULL, NULL),
(45, 'can_addedit_mods', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'modules', 'package', 'admin', 'bool', NULL, NULL),
(46, 'can_delete_mods', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'modules', 'package', 'admin', 'bool', NULL, NULL),
(47, 'can_addedit_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'admin', 'bool', NULL, NULL),
(48, 'can_edit_others_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'admin', 'bool', NULL, NULL),
(49, 'can_delete_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'admin', 'bool', NULL, NULL),
(50, 'can_change_pages_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'admin', 'bool', NULL, NULL),
(51, 'can_edit_quicklinks_order', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'quicklink_manager', 'package', 'admin', 'bool', NULL, NULL),
(52, 'can_addedit_quicklinks', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'quicklink_manager', 'package', 'admin', 'bool', NULL, NULL),
(53, 'can_delete_quicklinks', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'quicklink_manager', 'package', 'admin', 'bool', NULL, NULL),
(54, 'can_optimize_repair_tables', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'tools', 'package', 'admin', 'bool', NULL, NULL),
(55, 'can_clean_cache', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'tools', 'package', 'admin', 'bool', NULL, NULL),
(56, 'can_use_diags', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'tools', 'package', 'admin', 'bool', NULL, NULL),
(57, 'can_addedit_users', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'admin', 'bool', NULL, NULL),
(58, 'can_edit_users_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'admin', 'bool', NULL, NULL),
(59, 'can_force_logout_users', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'admin', 'bool', NULL, NULL),
(60, 'can_delete_users', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'admin', 'bool', NULL, NULL),
(61, 'can_change_usertitle', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'admin', 'bool', NULL, NULL),
(62, 'can_edit_usergroups_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'usergroup', 'package', 'admin', 'bool', NULL, NULL),
(63, 'can_addedit_usergroups', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'usergroup', 'package', 'admin', 'bool', NULL, NULL),
(64, 'can_login_admin_side', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'authorization', 'plugin', 'admin', 'bool', NULL, NULL),
(65, 'can_addedit_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(66, 'can_edit_others_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(67, 'can_publish_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(68, 'can_access_unpublished_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(69, 'can_rate_posts', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(70, 'can_edit_post_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(71, 'can_access_post_comments', 'a:3:{s:1:"*";s:4:"b:1;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(72, 'can_edit_others_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(73, 'can_change_comments_publish_status', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(74, 'can_delete_posts_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(75, 'can_access_unpublished_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(76, 'can_leave_comments', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(77, 'can_open_filemanager', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'filemanager', 'package', 'site', 'bool', NULL, NULL),
(78, 'can_upload_files', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'filemanager', 'package', 'site', 'bool', NULL, NULL),
(79, 'can_addedit_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'site', 'bool', NULL, NULL),
(80, 'can_edit_others_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'site', 'bool', NULL, NULL),
(81, 'can_change_pages_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'site', 'bool', NULL, NULL),
(82, 'can_access_unpublished_pages', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'pages', 'package', 'site', 'bool', NULL, NULL),
(83, 'can_edit_others_profilepage', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(84, 'can_change_usertitle', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(85, 'can_post_visitormessage', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(86, 'can_edit_others_visitormessage', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(87, 'can_access_memberlist', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(88, 'can_edit_others_profile_msg', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'user', 'package', 'site', 'bool', NULL, NULL),
(89, 'can_touch_comment_points', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:1;";i:2;s:4:"b:1;";}', 'blog', 'package', 'site', 'bool', NULL, NULL),
(90, 'can_addedit_domains', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'domains', 'package', 'admin', 'bool', NULL, NULL),
(91, 'can_delete_domains', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'domains', 'package', 'admin', 'bool', NULL, NULL),
(92, 'can_change_domains_activity', 'a:3:{s:1:"*";s:4:"b:0;";i:1;s:4:"b:0;";i:2;s:4:"b:1;";}', 'domains', 'package', 'admin', 'bool', NULL, NULL);


INSERT INTO `#__usergroupperms_value` (`usergroupperm`, `usergroup`, `value`) VALUES
(1, 1, 'b:0;'),(87, 2, 'b:1;'),(87, 2, 'b:1;'),(86, 2, 'b:1;'),(85, 2, 'b:1;'),(84, 2, 'b:1;'),(83, 2, 'b:1;'),(82, 2, 'b:1;'),(81, 2, 'b:1;'),
(80, 2, 'b:1;'),(79, 2, 'b:1;'),(78, 2, 'b:1;'),(77, 2, 'b:1;'),(76, 2, 'b:1;'),(75, 2, 'b:1;'),(74, 2, 'b:1;'),(73, 2, 'b:1;'),(72, 2, 'b:1;'),
(71, 2, 'b:1;'),(70, 2, 'b:1;'),(69, 2, 'b:1;'),(68, 2, 'b:1;'),(67, 2, 'b:1;'),(66, 2, 'b:1;'),(65, 2, 'b:1;'),(64, 2, 'b:1;'),(63, 2, 'b:1;'),
(62, 2, 'b:1;'),(61, 2, 'b:1;'),(60, 2, 'b:1;'),(59, 2, 'b:1;'),(58, 2, 'b:1;'),(57, 2, 'b:1;'),(56, 2, 'b:1;'),(55, 2, 'b:1;'),(54, 2, 'b:1;'),
(53, 2, 'b:1;'),(52, 2, 'b:1;'),(51, 2, 'b:1;'),(50, 2, 'b:1;'),(49, 2, 'b:1;'),(48, 2, 'b:1;'),(47, 2, 'b:1;'),(46, 2, 'b:1;'),(45, 2, 'b:1;'),
(44, 2, 'b:1;'),(43, 2, 'b:1;'),(42, 2, 'b:1;'),(41, 2, 'b:1;'),(40, 2, 'b:1;'),(39, 2, 'b:1;'),(38, 2, 'b:1;'),(37, 2, 'b:1;'),(36, 2, 'b:1;'),
(33, 2, 'b:1;'),(32, 2, 'b:1;'),(31, 2, 'b:1;'),(30, 2, 'b:1;'),(29, 2, 'b:1;'),(28, 2, 'b:1;'),
(26, 2, 'b:1;'),(25, 2, 'b:1;'),(24, 2, 'b:1;'),(23, 2, 'b:1;'),(22, 2, 'b:1;'),(21, 2, 'b:1;'),(20, 2, 'b:1;'),(19, 2, 'b:1;'),(18, 2, 'b:1;'),
(17, 2, 'b:1;'),(16, 2, 'b:1;'),(15, 2, 'b:1;'),(14, 2, 'b:1;'),(13, 2, 'b:1;'),(12, 2, 'b:1;'),(11, 2, 'b:1;'),(10, 2, 'b:1;'),(9, 2, 'b:1;'),
(8, 2, 'b:1;'),(7, 2, 'b:1;'),(6, 2, 'b:1;'),(5, 2, 'b:1;'),(4, 2, 'b:1;'),(3, 2, 'b:1;'),(2, 2, 'b:1;'),(1, 2, 'b:1;'),(2, 1, 'b:0;'),(3, 1, 'b:0;'),
(4, 1, 'b:0;'),(5, 1, 'b:0;'),(6, 1, 'b:0;'),(7, 1, 'b:0;'),(8, 1, 'b:0;'),(9, 1, 'b:0;'),(10, 1, 'b:0;'),(11, 1, 'b:0;'),(12, 1, 'b:0;'),(13, 1, 'b:0;'),
(14, 1, 'b:0;'),(15, 1, 'b:0;'),(16, 1, 'b:0;'),(17, 1, 'b:0;'),(18, 1, 'b:0;'),(19, 1, 'b:0;'),(20, 1, 'b:0;'),(21, 1, 'b:0;'),(22, 1, 'b:0;'),(23, 1, 'b:0;'),
(24, 1, 'b:0;'),(25, 1, 'b:0;'),(26, 1, 'b:0;'),(28, 1, 'b:0;'),(29, 1, 'b:0;'),(30, 1, 'b:0;'),(31, 1, 'b:0;'),(32, 1, 'b:0;'),(33, 1, 'b:0;'),
(36, 1, 'b:0;'),(37, 1, 'b:0;'),(38, 1, 'b:0;'),(39, 1, 'b:0;'),(40, 1, 'b:0;'),(41, 1, 'b:0;'),(42, 1, 'b:0;'),(43, 1, 'b:0;'),
(44, 1, 'b:0;'),(45, 1, 'b:0;'),(46, 1, 'b:0;'),(47, 1, 'b:0;'),(48, 1, 'b:0;'),(49, 1, 'b:0;'),(50, 1, 'b:0;'),(51, 1, 'b:0;'),(52, 1, 'b:0;'),(53, 1, 'b:0;'),
(54, 1, 'b:0;'),(55, 1, 'b:0;'),(56, 1, 'b:0;'),(57, 1, 'b:0;'),(58, 1, 'b:0;'),(59, 1, 'b:0;'),(60, 1, 'b:0;'),(61, 1, 'b:0;'),(62, 1, 'b:0;'),(63, 1, 'b:0;'),
(64, 1, 'b:0;'),(65, 1, 'b:0;'),(66, 1, 'b:0;'),(67, 1, 'b:0;'),(68, 1, 'b:0;'),(69, 1, 'b:1;'),(70, 1, 'b:0;'),(71, 1, 'b:1;'),(72, 1, 'b:0;'),(73, 1, 'b:0;'),
(74, 1, 'b:0;'),(75, 1, 'b:0;'),(76, 1, 'b:1;'),(77, 1, 'b:0;'),(78, 1, 'b:0;'),(79, 1, 'b:0;'),(80, 1, 'b:0;'),(81, 1, 'b:0;'),(82, 1, 'b:0;'),(83, 1, 'b:0;'),
(84, 1, 'b:0;'),(85, 1, 'b:1;'),(86, 1, 'b:0;'),(87, 1, 'b:1;'),(87, 1, 'b:1;'),(1, 0, 'b:0;'),(2, 0, 'b:0;'),(3, 0, 'b:0;'),(4, 0, 'b:0;'),(5, 0, 'b:0;'),
(6, 0, 'b:0;'),(7, 0, 'b:0;'),(8, 0, 'b:0;'),(9, 0, 'b:0;'),(10, 0, 'b:0;'),(11, 0, 'b:0;'),(12, 0, 'b:0;'),(13, 0, 'b:0;'),(14, 0, 'b:0;'),(15, 0, 'b:0;'),
(16, 0, 'b:0;'),(17, 0, 'b:0;'),(18, 0, 'b:0;'),(19, 0, 'b:0;'),(20, 0, 'b:0;'),(21, 0, 'b:0;'),(22, 0, 'b:0;'),(23, 0, 'b:0;'),(24, 0, 'b:0;'),(25, 0, 'b:0;'),
(26, 0, 'b:0;'),(28, 0, 'b:0;'),(29, 0, 'b:0;'),(30, 0, 'b:0;'),(31, 0, 'b:0;'),(32, 0, 'b:0;'),(33, 0, 'b:0;'),
(36, 0, 'b:0;'),(37, 0, 'b:0;'),(38, 0, 'b:0;'),(39, 0, 'b:0;'),(40, 0, 'b:0;'),(41, 0, 'b:0;'),(42, 0, 'b:0;'),(43, 0, 'b:0;'),(44, 0, 'b:0;'),(45, 0, 'b:0;'),
(46, 0, 'b:0;'),(47, 0, 'b:0;'),(48, 0, 'b:0;'),(49, 0, 'b:0;'),(50, 0, 'b:0;'),(51, 0, 'b:0;'),(52, 0, 'b:0;'),(53, 0, 'b:0;'),(54, 0, 'b:0;'),(55, 0, 'b:0;'),
(56, 0, 'b:0;'),(57, 0, 'b:0;'),(58, 0, 'b:0;'),(59, 0, 'b:0;'),(60, 0, 'b:0;'),(61, 0, 'b:0;'),(62, 0, 'b:0;'),(63, 0, 'b:0;'),(64, 0, 'b:0;'),(65, 0, 'b:0;'),
(66, 0, 'b:0;'),(67, 0, 'b:0;'),(68, 0, 'b:0;'),(69, 0, 'b:0;'),(70, 0, 'b:0;'),(71, 0, 'b:1;'),(72, 0, 'b:0;'),(73, 0, 'b:0;'),(74, 0, 'b:0;'),(75, 0, 'b:0;'),
(76, 0, 'b:0;'),(77, 0, 'b:0;'),(78, 0, 'b:0;'),(79, 0, 'b:0;'),(80, 0, 'b:0;'),(81, 0, 'b:0;'),(82, 0, 'b:0;'),(83, 0, 'b:0;'),(84, 0, 'b:0;'),(85, 0, 'b:0;'),
(86, 0, 'b:0;'),(87, 0, 'b:0;'),(87, 0, 'b:0;'),(88, 0, 'b:0;'),(88, 1, 'b:0;'),(88, 2, 'b:1;'),(89, 0, 'b:0;'),(89, 1, 'b:1;'),(89, 2, 'b:1;'),
(90, 0, 'b:0;'),(90, 1, 'b:0;'),(90, 2, 'b:1;'),(91, 0, 'b:0;'),(91, 1, 'b:0;'),(91, 2, 'b:1;'),(92, 0, 'b:0;'),(92, 1, 'b:0;'),(92, 2, 'b:1;');

-- a little hack for inserting guest as id=0
-- first, insert with id=1
INSERT INTO `#__usergroups` (`id`, `name`, `title`, `active`) VALUES
(0, 'guest', 'Guest', 1);

-- update id to id=0
UPDATE `#__usergroups` SET `id`='0' WHERE `id`='1';

-- insert other two
INSERT INTO `#__usergroups` (`id`, `name`, `title`, `active`) VALUES
(1, 'registered', 'Registered', 1),
(2, 'administrator', 'Administrator', 1);


INSERT INTO `#__webservices` (`id`, `webservice`, `title`, `enabled`, `core`) VALUES
(1, 'info', 'Website Information', 1, 1),
(2, 'api_metaweblog', 'MetaWeblog API', 1, 1);
